name: workflow-docker-release

on:
  push:
    tags:
      - '*'

jobs:
  call-reusable-workflow:
    uses: binhex/workflow-templates/.github/workflows/workflow-docker-release.yml@main
    with:
      tags: ${{ github.event.inputs.tags }}
      platforms: linux/amd64,linux/arm64
    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
      IMMORTALITY_PAT: ${{ secrets.IMMORTALITY_PAT }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      TDB_PAT: ${{ secrets.TDB_PAT }}
